version: "3"
services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: yihong524/django:v1
    ports:
    - 8000:8000    # 如果不想开放这个端口到外面，就写成 - 8000
    volumes:
      - "static:/src/app/statics"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: yihong524/nginx:v1
    ports:
      - 8080:80
    volumes:
      - "static:/var/www/html"
volumes:
  static: